insert into Colors(ColorId,ColorName) values (1,'Blue')
insert into Colors(ColorId,ColorName) values (2,'Yellow')
insert into Colors(ColorId,ColorName) values (3,'White')
insert into Colors(ColorId,ColorName) values (4,'Black')
insert into Colors(ColorId,ColorName) values (5,'Red')