insert into Customers(CustomerId,CustomerName,City) values (1,'Blue Man','America')
insert into Customers(CustomerId,CustomerName,City) values (2,'White Man','New York')
insert into Customers(CustomerId,CustomerName,City) values (3,'Red WoMan','Berlin')
insert into Customers(CustomerId,CustomerName,City) values (4,'Adam Black','Ankara')
insert into Customers(CustomerId,CustomerName,City) values (5,'Admin Blue','İstanbul')
insert into Customers(CustomerId,CustomerName,City) values (6,'John Green','Hon kong')
insert into Customers(CustomerId,CustomerName,City) values (7,'White Rose','Java')
insert into Customers(CustomerId,CustomerName,City) values (8,'Ben Jen','İtalya')
insert into Customers(CustomerId,CustomerName,City) values (9,'Rise OfMan','Viyana')
insert into Customers(CustomerId,CustomerName,City) values (10,'Clara Black','Fransa')